import type { HistoryItem, SavePostData } from '../../types';

export interface StorageProvider {
  /**
   * Save a generated post and the related product
   */
  savePost(data: SavePostData): Promise<string>;

  /**
   * Fetch all history items generated by the user
   */
  getHistory(): Promise<HistoryItem[]>;

  /**
   * Backup the whole database into a JSON string
   */
  exportBackup(): Promise<string>;

  /**
   * Restore the whole database from a JSON string
   */
  importBackup(jsonData: string): Promise<void>;
}
